include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    require_trailing_commas: true
    avoid_print: true
    unawaited_futures: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    sort_child_properties_last: true
    curly_braces_in_flow_control_structures: true
